[firebase]

apiKey = "AIzaSyDx3NAI38pEgl_Peh7kR_pWRYmAKKYC_-0"
authDomain = "fake-news-detector-e319f.firebaseapp.com"
projectId = "fake-news-detector-e319f"
storageBucket = "fake-news-detector-e319f.firebasestorage.app"
messagingSenderId = "251097941867"
appId = "1:251097941867:web:27fa834d865175993a6e2e"
measurementId = "G-7ELQC8NBZZ"

[firebase_service_account]

type = "service_account"
project_id = "fake-news-detector-e319f"
private_key_id = "706aa0b44024a1cf8ec1fac5aeca7172829d6c11"

private_key =  "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDM2/iuQnkKtD+Y\nc+er9QAYH+01oFtVpC5gtgABln0wlB9yVSBof9Kzm1ysMetr3ud4NOGCU18d55hc\njupM7e/uT3ymZd/c6nf4ooFtf4K13HcaHWe8n767smCpoDkzgMcnZeAuW/4WwKIw\nQVDtDtrPPFPeDtglTqeQKwuZhEISJF/GVG0qw8zPJUpQ4xzWJ69FoKA4rC57em8+\nHTkv0oIQAsRCmReNSR0QcV8zAkyUUm+rJ+d1lSS3NihWa2pY/7N21mVI/b7lPEGQ\n13FAVIz2GaGDqJGb8WDWcjVmPPjquJTxsfSCNUxMwDlKQ5kSdavfUPWog+WMLvee\n/vP+jwqDAgMBAAECggEABSJcNK3Yz8Jdt6nr+/zLcE9YiBgJQfe369eT33ZQk+ea\ndCibA9N0SekSZQRpRI5VGcelgTkqsJqt0GAKkjwCX+QhGSCDgEtmD1avTLm94mXw\nnDhxcaJFSvn4/zdTR62qEBw3BqJql1Jjnjb82rwdEsWNyopvs1upymyxwTq11zOD\nsjSmPfyYM3o2hG6+GX4+o0PtL8Cc/TlVM9EDSVIiNlJa0ZRtup7efAqeoxnVsqAI\n6M2YAoBKX+aj6sz2JUv4aMHbXssbvYTbAjTiDtW4IS1J5DB+CsPR3OS+YhvaHUdX\n0UjTpkokOsAiVSDJW4zjdlKyz/ODiEbeYfwkc8V5ZQKBgQDnXDUMLxmGTsiOKjgI\nyPNIbrroYmQ3ebYE1zjaulgh6brqAMSuTrOghckZfnl1T/hzqIhMnEI/B84OykIP\neK0m9d2a6LB3nqILlUDaLVxjp8S8CAPjurkA0DJD44A2OpcMJAzRbOaHJ6eD+11+\nId99Sdlj1d7sn09afj68umjdDQKBgQDirT6PGK44dnqBSo2xltpzOo9NH30TUiQM\nFVgARHj3uvXtIFv2DmhtNA+UYU9IMZyv5d3mbRw1sH7ORr6tXSXw15aoJDifKTU1\nlVxpw0gfgMPbqs8db3bG78oR89ridowgq0FlngeKA0vRPoPWdvo9+yQB8NSXE+6N\nLNN5cTRBzwKBgQCS9MLNRm2UHh7ODoshKWM+svcN/NFjW2/+iyaV6J9qiygq0uob\nPepjIBeolelYVr+d14McBnUdzDtasaZcZW62vJ1SdFMC6ERNzzQuYXm54yrXtM+j\nq0sv9Q64iJ071ON01sE9lUqotst0zgmIwMNQtcPb4lGDQ34IIQCAqHdLUQKBgQCO\nLeJmeTGWIuJ2RGAZ+ygsTJfj5RNb0hLgLWcUS96gbHmi8cAc1y6zCIuZI2xKOSwx\nvHnx9ZBTMNBo7EDfluSca22JK6cEViGU6YmcoSuU7vxqxXnB2c9jurZBinZJw9fj\nCegsJ/JMpAKjTZX+KISP6f3M5dVCqfLgRDSlINeJSwKBgDU1liA6slDMXV/efevZ\nzhIDeUttlfMqVs1hXSYiFbS0NMnnoH0TgX6MZgRvEr1GPaBfCMzSErw09beAgS6M\n2uvJFsUKRFTtSMr8FIXMCTlz7d1nhaoN1M4yPghRzJV5HuhfEjuuZbt0eZ2l/N61\n9hY/oGCfAz/RkCTc62xhkgNq\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@fake-news-detector-e319f.iam.gserviceaccount.com"
client_id = "103548275174037060658"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40fake-news-detector-e319f.iam.gserviceaccount.com"
universe_domain = "googleapis.com"